version: '3'

networks: 
    "laravel_net":
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: "laravel_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT}:8000"
        volumes: 
            - ./:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - db
        networks: 
            - "laravel_net"

    db:
        image: mysql:8.0
        container_name: "laravel_db"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        networks:
            - "laravel_net"

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_docker:latest
        container_name: "laravel_php"
        restart: unless-stopped
        tty: true
        working_dir: /app
        volumes: 
            - ./:/app
        ports: 
            - "${PHP_PORT}:9000"
        networks: 
            - "laravel_net"

    redis:
        image: redis:alpine
        container_name: "laravel_redis"
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - "laravel_net"